{% set name = "pyPGCF" %}
{% set version = "0.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: "https://github.com/m-nikolaidis/pyPGCF"
  git_depth: 1
  #url: "https://github.com/Marios-Nikolaidis/{{ name }}/archive/refs/tags/{{ version }}.tar.gz"
  #sha256: 376f50e05b60f5c6f7b8316b98490d2aa30d6363c7cbb447aa2e75b7b5ef7e4c

build:
  number: 0
  noarch: python
  # entry_points:
  #   console_scripts:
  #     pyPGCF = pypgcf.pyPGCF:main
  #
requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - iqtree >=2.*
    - gblocks
    - muscle ==3.8.*
    - pandas
    - xlsxwriter
    - openpyxl
    - tqdm
    - eggnog-mapper
    - biopython ==1.78
    - antismash
    - diamond ==2.0.9

about:
  home: "https://github.com/Marios-Nikolaidis/pyPGCF"
  license: GPL
  license_file: LICENSE
  summary: "pyPGCF: PhyloGenomic, Core and Fingerprint analyses package"

extra:
  recipe-maintainers:
    - "Marios Nikolaidis"
