{% set name = "pyPGCF" %}
{% set version = "0.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: "https://github.com/m-nikolaidis/pyPGCF"
  git_depth: 1

build:
  number: 0
  noarch: python
requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - iqtree >=2.*
    - gblocks
    - muscle ==3.8.*
    - pandas
    - xlsxwriter
    - openpyxl
    - tqdm
    - eggnog-mapper
    - biopython ==1.78
    - antismash ==6.1.1
    - diamond ==2.0.9

about:
  home: "https://github.com/Marios-Nikolaidis/pyPGCF"
  license: GPL
  license_file: LICENSE
  summary: "pyPGCF: PhyloGenomic, Core and Fingerprint analyses package"

extra:
  recipe-maintainers:
    - "Marios Nikolaidis"
