{% set name = "pyPGCF" %}
{% set version = "0.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: "https://github.com/m-nikolaidis/pyPGCF"
  git_depth: 1

build:
  number: 0
  noarch: python
requirements:
  host:
    - pip
    - python ==3.9.*
  run:
    - python ==3.9.*
    - iqtree >=2.*
    - gblocks
    - muscle ==3.8.*
    - pandas
    - openpyxl
    - tqdm
    - eggnog-mapper
    - antismash ==7.1.0
    - mcl
    - biopython ==1.78.*

about:
  home: "https://github.com/m-nikolaidis/pyPGCF"
  license: GPL
  license_file: LICENSE
  summary: "pyPGCF: PhyloGenomic, Core and Fingerprint analyses package"

extra:
  recipe-maintainers:
    - "Marios Nikolaidis"
